---
title: "population_trends"
output: html_document
date: "2026-03-31"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#required packages
knitr::opts_chunk$set(echo = TRUE, warning = F, message=F)
library(tidyverse)
library(broom)
library(summariser)
library(ggpubr)
```

#Count data formatting
```{r count_data}
#read data
dat=read.csv2("./data/Count_Data.csv")
head(dat)

#filter and summarise data
dat2=dat %>% 
  filter(month==12|month==1 |month==2  |month==3 ) %>% #keep counts from Dec-Mar
  select(WinterNr,year,month,day,Mdau,Mmyo,Mnat) %>% 
  mutate(date=as.Date(paste0(year,"-",month,"-",day))) %>% 
  group_by(date,WinterNr) %>% 
  summarise(Mdau=sum(Mdau), Mnat=sum(Mnat), Mmyo=sum(Mmyo))

#pivot to long format
dat2_long= dat2 %>% 
  pivot_longer(cols = c(Mdau, Mnat, Mmyo),
               names_to = "species",
               values_to = "count")

# Create a 'month_day' date with dummy year (plots align on calendar date)
dat2_long = dat2_long %>%
  mutate(month_day = as.Date(format(date, "2000-%m-%d"))) %>% 
  ungroup()
year(dat2_long$month_day) <- ifelse(month(dat2_long$date) > 7, 1999, 2000)
```


#COMPARISON OF POPULATION TRENDS with 3 different approaches
```{r settings}
set.seed(42)
# Set number of iterations
n_iter=100
```

#Resampling
```{r random_resampling1}
#METHOD 1
#random counts from the typical hibernation survey period: 1 Dec - 15 Mar 
random_samples1=
  map_dfr(1:n_iter, function(i) {
  dat2_long %>%
    filter(month_day >= as.Date("1999-12-01") & month_day <= as.Date("2000-03-15")) %>% 
    group_by(WinterNr, species) %>%
    sample_n(1) %>%  # sample 1 random count per species per winter
    mutate(iteration = i) %>%
    ungroup()
})
#View(random_samples1)

#METHOD 2
#random counts within the core hibernation period (1 Jan - 15 Feb) based on light barrier activity (minimumum net movement)
random_samples2=
  map_dfr(1:n_iter, function(i) {
  dat2_long %>%
    filter(month_day >= as.Date("2000-01-01") & month_day <= as.Date("2000-02-15")) %>% 
    group_by(WinterNr, species) %>%
    sample_n(1) %>%  # sample 1 random count per species per winter
    mutate(iteration = i) %>%
    ungroup()
})
#View(random_samples2)

#METHOD 3
#random counts within core hibernation period (1 Jan - 15 Feb), closest to reference dates (with dummy year 2000)
ref_dates <- as.Date(c("2000-01-07","2000-01-14","2000-01-21",
                       "2000-01-28","2000-02-04","2000-02-11"))

df_grouped= 
  dat2_long %>%
    filter(month_day >= as.Date("2000-01-01") 
           & month_day <= as.Date("2000-02-18")) %>%
  # expand grid of data × reference dates
  crossing(ref_date = ref_dates) %>%
  # keep only rows where month_day is within ±7 days of ref_date
  filter(between(as.numeric(month_day - ref_date), -7, 7))
#View(df_grouped)


#METHOD 3 A
#random counts within core hibernation period (1 Jan - 15 Feb), closest to reference dates (with dummy year 2000), but only JANUARY counts for Mnat
ref_dates2 <- as.Date(c("2000-01-07","2000-01-14","2000-01-21",
                       "2000-01-28"))

df_grouped2= 
  dat2_long %>%
    filter(species=="Mnat") %>% 
    filter(month_day >= as.Date("2000-01-01") 
           & month_day <= as.Date("2000-01-28")) %>%
  # expand grid of data × reference dates
  crossing(ref_date = ref_dates2) %>%
  # keep only rows where month_day is within ±7 days of ref_date
  filter(between(as.numeric(month_day - ref_date), -7, 7))
```

#Population trend estimates
```{r random_trends}
trends1=
  random_samples1 %>%
  group_by(iteration, species) %>%
  summarise(
    model = list(lm(count ~ WinterNr)),
    .groups = "drop"
  ) %>%
  mutate(tidy_model = map(model, tidy)) %>%
  unnest(tidy_model) %>%
  filter(term == "WinterNr")  # extract slope

trends2=
  random_samples2 %>%
  group_by(iteration, species) %>%
  summarise(
    model = list(lm(count ~ WinterNr)),
    .groups = "drop"
  ) %>%
  mutate(tidy_model = map(model, tidy)) %>%
  unnest(tidy_model) %>%
  filter(term == "WinterNr")  # extract slope

trends3=
  df_grouped %>%
  group_by(ref_date, species) %>%
  summarise(
    model = list(lm(count ~ WinterNr)),
    .groups = "drop"
  ) %>%
  mutate(tidy_model = map(model, tidy)) %>%
  unnest(tidy_model) %>%
  filter(term == "WinterNr")  # extract slope

trends3a=
  df_grouped2 %>%
  group_by(ref_date) %>%
  summarise(
    model = list(lm(count ~ WinterNr)),
    .groups = "drop"
  ) %>%
  mutate(tidy_model = map(model, tidy)) %>%
  unnest(tidy_model) %>%
  filter(term == "WinterNr")  # extract slope
```

#Extract trend slopes
```{r slopes}
# Calculate slope direction for each iteration and species
slope_signs1 =
  random_samples1 %>%
  group_by(iteration, species) %>%
  summarise(
    slope = coef(lm(count ~ WinterNr))[["WinterNr"]],
    .groups = "drop"
  ) %>%
  mutate(trend_dir = ifelse(slope >= 0, "positive", "negative"))

slope_signs2 =
  random_samples2 %>%
  group_by(iteration, species) %>%
  summarise(
    slope = coef(lm(count ~ WinterNr))[["WinterNr"]],
    .groups = "drop"
  ) %>%
  mutate(trend_dir = ifelse(slope >= 0, "positive", "negative"))

slope_signs3 =
  df_grouped %>%
  group_by(ref_date, species) %>%
  summarise(
    slope = coef(lm(count ~ WinterNr))[["WinterNr"]],
    .groups = "drop"
  ) %>%
  mutate(trend_dir = ifelse(slope >= 0, "positive", "negative"))


slope_signs3a =
  df_grouped2 %>%
  group_by(ref_date) %>%
  summarise(
    slope = coef(lm(count ~ WinterNr))[["WinterNr"]],
    .groups = "drop"
  ) %>%
  mutate(trend_dir = ifelse(slope >= 0, "positive", "negative"))


# Join slope sign back to the main data
random_counts_labeled1 =
  random_samples1 %>%
  left_join(slope_signs1, by = c("iteration", "species"))

random_counts_labeled2 =
  random_samples2 %>%
  left_join(slope_signs2, by = c("iteration", "species"))

random_counts_labeled3 =
  df_grouped %>%
  left_join(slope_signs3, by = c("ref_date", "species"))

random_counts_labeled3a =
  df_grouped2 %>%
  left_join(slope_signs3a, by = c("ref_date"))
```

#Summary table
```{r results_table}
#METHOD 1
random_counts_labeled1 %>% 
  filter(WinterNr==19) %>% #to keep one value per iteration
  group_by(species) %>% 
  summarise(min_slope=min(slope),
            max_slope=max(slope))

random_counts_labeled1 %>% 
  filter(WinterNr==19) %>%
  group_by(species) %>% 
  count(trend_dir)

variance1=random_counts_labeled1 %>% 
  filter(WinterNr==19) %>%
  group_by(species,iteration) %>% 
  slice_head(n=1) %>%
  group_by(species) %>% 
  summary_stats(slope)
# variance1
# write.table(variance1, "clipboard", sep="\t")


#METHOD 2
random_counts_labeled2 %>% 
  filter(WinterNr==19) %>%
  group_by(species) %>% 
  summarise(min_slope=min(slope),
            max_slope=max(slope))

random_counts_labeled2 %>% 
  filter(WinterNr==19) %>%
  group_by(species) %>% 
  count(trend_dir)

variance2=random_counts_labeled2 %>% 
  filter(WinterNr==19) %>%
  group_by(species,iteration) %>% 
  slice_head(n=1) %>%
  group_by(species) %>% 
  summary_stats(slope)
# variance2
# write.table(variance2, "clipboard", sep="\t")


#METHOD 3
random_counts_labeled3 %>% 
  filter(WinterNr==19) %>%
  group_by(species) %>% 
  summarise(min_slope=min(slope),
            max_slope=max(slope))

random_counts_labeled3 %>% 
  group_by(species) %>% 
  distinct(slope, .keep_all = T)  %>%
  group_by(species) %>% 
  count(trend_dir)

variance3=random_counts_labeled3 %>% 
  group_by(species,ref_date) %>% 
  slice_head(n=1) %>%
  group_by(species) %>% 
  summary_stats(slope)
# variance3
# write.table(variance3, "clipboard", sep="\t")


#METHOD 3A
random_counts_labeled3a %>% 
  filter(WinterNr==19) %>%
   summarise(min_slope=min(slope),
            max_slope=max(slope))

random_counts_labeled3a %>% 
  distinct(ref_date, .keep_all = T)  %>%
  count(trend_dir)

variance3a=random_counts_labeled3a %>% 
  distinct(ref_date, .keep_all = T)  %>%
  group_by(ref_date) %>% 
  slice_head(n=1) %>% 
  ungroup() %>% 
  summary_stats(slope)

```

#Plots
```{r slopes_plot}
#METHOD 1
# plot with lines colored by trend direction
method1_plot=ggplot(random_counts_labeled1, aes(x = WinterNr, y = count, group = interaction(iteration, species))) +
  # Random sample trends
  geom_smooth(
    method = "lm",
    se = FALSE,
    aes(color = trend_dir),
    alpha = 0.5,
    linewidth = 0.4,
    show.legend = T
  ) +
  facet_wrap(~species, scales = "free_y",labeller = labeller(species = c(Mdau = "Myotis daubentonii", Mmyo = "Myotis myotis", Mnat = "Myotis nattereri"))) +
  scale_color_manual(values = c("positive" = "blue", "negative" = "red")) +
  labs(
    x = "Year",
    y = "Visual count",
    title = "Full hibernation survey period (1 Dec - 15 Mar)",
    color="trend direction") +
  theme_classic()+
  theme(strip.text.x.top = element_text(face = "italic"),
        legend.position = "bottom")
method1_plot


#METHOD 2
# plot with lines colored by trend direction
method2_plot=ggplot(random_counts_labeled2, aes(x = WinterNr, y = count, group = interaction(iteration, species))) +
  # Random sample trends
  geom_smooth(
    method = "lm",
    se = FALSE,
    aes(color = trend_dir),
    alpha = 0.5,
    linewidth = 0.4,
    show.legend = T
  ) +
  facet_wrap(~species, scales = "free_y",labeller = labeller(species = c(Mdau = "Myotis daubentonii", Mmyo = "Myotis myotis", Mnat = "Myotis nattereri"))) +
  scale_color_manual(values = c("positive" = "blue", "negative" = "red")) +
  labs(
    x = "Year",
    y = "Visual count",
    title = "Core hibernation period (1 Jan - 15 Feb)",
    color="trend direction") +
  theme_classic()+
  theme(strip.text.x.top = element_text(face = "italic"),
        legend.position = "bottom")
method2_plot


#METHOD 3
random_counts_labeled3$ref_date_plot=format(as.Date(random_counts_labeled3$ref_date), "%d %b")

random_counts_labeled3$ref_date_plot=factor(random_counts_labeled3$ref_date_plot, levels=c("07 Jan","14 Jan","21 Jan", "28 Jan", "04 Feb","11 Feb"))

# plot with lines colored by trend direction
method3_plot=ggplot(random_counts_labeled3, aes(x = WinterNr, y = count, group = interaction(ref_date, species))) +
  # Random sample trends
  geom_smooth(
    method = "lm",
    se = FALSE,
    aes(color = ref_date_plot),
    alpha = 0.5,
    linewidth = 0.7,
    show.legend = T
  ) +
   facet_wrap(~species, scales = "free_y",labeller = labeller(species = c(Mdau = "Myotis daubentonii", Mmyo = "Myotis myotis", Mnat = "Myotis nattereri"))) +
  labs(
    x = "Year",
    y = "Visual count",
    title = "Consistent count date (1 Jan - 15 Feb)",
    color="reference date"
    
  ) +
  theme_classic()+
  theme(strip.text.x.top = element_text(face = "italic"))+
  theme(legend.position = "bottom")+ 
  scale_color_manual(values = c("#3b8132","#72bf6a","#61e529","#9FE2BF", "#f01c9c","#FF64dc"))+
  guides(
  colour = guide_legend(
    nrow = 1,
    override.aes = list(linewidth = 2)
  )
)
method3_plot
```

```{r merged_plot}
merged_plot=ggarrange(method1_plot,method2_plot,method3_plot, ncol=1,
                      labels = toupper(paste0(letters[1:3],")")))
ggsave(paste0("./plots/population_trends_merged.png"),width = 21, height = 29, units = "cm")
```

